package com.lzc.basicssm.entity;

import java.util.Date;

public class Diary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.user_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.type_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.create_time
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.title
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.content
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.id
     *
     * @return the value of diary.id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.id
     *
     * @param id the value for diary.id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.user_id
     *
     * @return the value of diary.user_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.user_id
     *
     * @param userId the value for diary.user_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.type_id
     *
     * @return the value of diary.type_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.type_id
     *
     * @param typeId the value for diary.type_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.create_time
     *
     * @return the value of diary.create_time
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.create_time
     *
     * @param createTime the value for diary.create_time
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.title
     *
     * @return the value of diary.title
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.title
     *
     * @param title the value for diary.title
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.content
     *
     * @return the value of diary.content
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.content
     *
     * @param content the value for diary.content
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    public String toString() {
        return "Diary{" +
                "id=" + id +
                ", userId=" + userId +
                ", typeId=" + typeId +
                ", createTime=" + createTime +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                '}';
    }
}