package com.lzc.basicssm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DiaryTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public DiaryTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("type_name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("type_name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("type_name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("type_name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("type_name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("type_name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("type_name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("type_name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("type_name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("type_name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("type_name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("type_name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("type_name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("type_name not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberIsNull() {
            addCriterion("diary_number is null");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberIsNotNull() {
            addCriterion("diary_number is not null");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberEqualTo(Integer value) {
            addCriterion("diary_number =", value, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberNotEqualTo(Integer value) {
            addCriterion("diary_number <>", value, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberGreaterThan(Integer value) {
            addCriterion("diary_number >", value, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("diary_number >=", value, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberLessThan(Integer value) {
            addCriterion("diary_number <", value, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberLessThanOrEqualTo(Integer value) {
            addCriterion("diary_number <=", value, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberIn(List<Integer> values) {
            addCriterion("diary_number in", values, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberNotIn(List<Integer> values) {
            addCriterion("diary_number not in", values, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberBetween(Integer value1, Integer value2) {
            addCriterion("diary_number between", value1, value2, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andDiaryNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("diary_number not between", value1, value2, "diaryNumber");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andImportantLevelIsNull() {
            addCriterion("important_level is null");
            return (Criteria) this;
        }

        public Criteria andImportantLevelIsNotNull() {
            addCriterion("important_level is not null");
            return (Criteria) this;
        }

        public Criteria andImportantLevelEqualTo(String value) {
            addCriterion("important_level =", value, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelNotEqualTo(String value) {
            addCriterion("important_level <>", value, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelGreaterThan(String value) {
            addCriterion("important_level >", value, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelGreaterThanOrEqualTo(String value) {
            addCriterion("important_level >=", value, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelLessThan(String value) {
            addCriterion("important_level <", value, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelLessThanOrEqualTo(String value) {
            addCriterion("important_level <=", value, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelLike(String value) {
            addCriterion("important_level like", value, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelNotLike(String value) {
            addCriterion("important_level not like", value, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelIn(List<String> values) {
            addCriterion("important_level in", values, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelNotIn(List<String> values) {
            addCriterion("important_level not in", values, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelBetween(String value1, String value2) {
            addCriterion("important_level between", value1, value2, "importantLevel");
            return (Criteria) this;
        }

        public Criteria andImportantLevelNotBetween(String value1, String value2) {
            addCriterion("important_level not between", value1, value2, "importantLevel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table diary_type
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 02 13:44:56 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table diary_type
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}