package com.lzc.basicssm.entity;

import java.util.Date;

public class LoginUser {

    private UserInfo userInfo;

    public UserInfo getUserInfo() {
        return userInfo;
    }

    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.username
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.password
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.role_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.last_login_time
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.id
     *
     * @return the value of login_user.id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.id
     *
     * @param id the value for login_user.id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.username
     *
     * @return the value of login_user.username
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.username
     *
     * @param username the value for login_user.username
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.password
     *
     * @return the value of login_user.password
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.password
     *
     * @param password the value for login_user.password
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.role_id
     *
     * @return the value of login_user.role_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.role_id
     *
     * @param roleId the value for login_user.role_id
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.last_login_time
     *
     * @return the value of login_user.last_login_time
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.last_login_time
     *
     * @param lastLoginTime the value for login_user.last_login_time
     *
     * @mbggenerated Thu Aug 02 13:44:56 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}