package com.lzc.basicssm.entity;

public class RoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.id
     *
     * @mbggenerated Thu Aug 02 13:49:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.role
     *
     * @mbggenerated Thu Aug 02 13:49:42 CST 2018
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.id
     *
     * @return the value of role_user.id
     *
     * @mbggenerated Thu Aug 02 13:49:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.id
     *
     * @param id the value for role_user.id
     *
     * @mbggenerated Thu Aug 02 13:49:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.role
     *
     * @return the value of role_user.role
     *
     * @mbggenerated Thu Aug 02 13:49:42 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.role
     *
     * @param role the value for role_user.role
     *
     * @mbggenerated Thu Aug 02 13:49:42 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}