package com.lzc.basicssm.dao;

import com.lzc.basicssm.entity.LoginUser;
import com.lzc.basicssm.entity.UserInfo;

public interface UserDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jul 23 14:05:51 CST 2018
     */
    LoginUser selectByUserName(String username);


    UserInfo selectInfoByName(String name);
}